sudo: required
dist: xenial

language:
  - minimal
  - cpp

os:
  - linux
  
compiler:
  - gcc
  - clang
  
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtbase5-dev libqt5svg5-dev libqt5opengl5-dev 
 - sudo apt-get install qt5-default qttools5-dev-tools libdw-dev 
 
before_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4

notifications:
  email:
    recipients:
      - davide.faconti@gmail.com
    on_success: change
on_failure: always
